# Generated by Django 2.1.3 on 2018-12-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='basic_cover_count',
        ),
        migrations.RemoveField(
            model_name='client',
            name='customer_count',
        ),
        migrations.RemoveField(
            model_name='client',
            name='fully_comp_count',
        ),
        migrations.AddField(
            model_name='client',
            name='account_number',
            field=models.CharField(default=0, max_length=16),
        ),
    ]
