"""
Django settings for aem project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%ng79^xhmwgvq+a35bn65kt*vs#whkiekq*0gn&g%+^!2wyk*q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
if DEBUG:
    ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'silk',

    'aemauthentication.apps.AuthenticationConfig',
    'company.apps.CompanyConfig',
    'core.apps.CoreConfig',
    'clients.apps.ClientsConfig',
    'groups.apps.GroupsConfig',
    'customers.apps.CustomersConfig',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'aemauthentication.backends.JWTAuthentication',

    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],

    'EXCEPTION_HANDLER': 'core.exceptions.core_exception_handler',
    'NON_FIELD_ERRORS_KEY': 'error',

}

AUTH_USER_MODEL = 'aemauthentication.User'

# JWT settings
JWT_AUTH = {
    'JWT_ENCODE_HANDLER':
        'rest_framework_jwt.utils.jwt_encode_handler',

    'JWT_DECODE_HANDLER':
        'rest_framework_jwt.utils.jwt_decode_handler',

    'JWT_PAYLOAD_HANDLER':
        'rest_framework_jwt.utils.jwt_payload_handler',

    'JWT_PAYLOAD_GET_USER_ID_HANDLER':
        'rest_framework_jwt.utils.jwt_get_user_id_from_payload_handler',

    'JWT_RESPONSE_PAYLOAD_HANDLER':
        'rest_framework_jwt.utils.jwt_response_payload_handler',

    'JWT_SECRET_KEY': SECRET_KEY,
    'JWT_GET_USER_SECRET_KEY': None,
    'JWT_PUBLIC_KEY': None,
    'JWT_PRIVATE_KEY': None,
    'JWT_ALGORITHM': 'HS256',
    'JWT_VERIFY': True,
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LEEWAY': 0,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=300),
    'JWT_AUDIENCE': None,
    'JWT_ISSUER': None,

    'JWT_ALLOW_REFRESH': False,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),

    'JWT_AUTH_HEADER_PREFIX': 'Bearer',
    'JWT_AUTH_COOKIE': None,
}

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')

MIDDLEWARE = [
    'silk.middleware.SilkyMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aem.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

"""
 USER GROUPS AND PERMISSION CONSTANTS
"""

# Aem Group linked_group names (Names of the Group to associate the AemGroup with.
AEM_ADMIN_LINKED_GROUP_NAME = "Aem Admin"
AEM_EMPLOYEE_LINKED_GROUP_NAME = "Aem Employee"
AEM_CUSTOMER_SUPER_USER_LINKED_GROUP_NAME = "Aem Customer Super User"
AEM_CUSTOMER_ADMIN_LINKED_GROUP_NAME = "Aem Customer Admin"
AEM_CUSTOMER_USER_LINKED_GROUP_NAME = "Aem Customer User"

# Slug fields for user groups
AEM_SUPER_USER_SLUG_FIELD = "aem-super-user"
AEM_ADMIN_SLUG_FIELD = "aem-admin"
AEM_EMPLOYEE_SLUG_FIELD = "aem-employee"
AEM_CUSTOMER_SUPER_USER_SLUG_FIELD = "aem-customer-super-user"
AEM_CUSTOMER_ADMIN_SLUG_FIELD = "aem-customer-admin"
AEM_CUSTOMER_USER_SLUG_FIELD = "aem-customer-user"

# Slug fields for creating clients
ADD_CLIENT_PERMISSION = "clients.add_client"
ADD_CUSTOMER_PERMISSION = "customers.add_customer"
ADD_COMPANY_PERMISSION = "company.add_company"
VIEW_COMPANY_PERMISSION = "company.view_company"

"""
    PERMISSIONS
    
    These permissions outline the permissions that each user type has access to. 
    These are mainly used in tests to assure that the correct access is given.
"""

# USER PERMISSIONS
AEM_ADMIN_CAN_ADD_USER_PERMISSIONS = (
    AEM_EMPLOYEE_SLUG_FIELD,
)

AEM_EMPLOYEE_CAN_ADD_USER_PERMISSIONS = (
)

AEM_CUSTOMER_SUPER_USER_CAN_ADD_USER_PERMISSIONS = (
    AEM_CUSTOMER_ADMIN_SLUG_FIELD,
    AEM_CUSTOMER_USER_SLUG_FIELD,
)

AEM_CUSTOMER_ADMIN_CAN_ADD_USER_PERMISSIONS = (
    AEM_CUSTOMER_USER_SLUG_FIELD,
)

AEM_CUSTOMER_USER_CAN_ADD_USER_PERMISSIONS = (
)

# CLIENT PERMISSIONS
AEM_ADMIN_CLIENT_PERMISSIONS = (
)

AEM_EMPLOYEE_CLIENT_PERMISSIONS = (
)

AEM_CUSTOMER_SUPER_USER_CLIENT_PERMISSIONS = (
    ADD_CLIENT_PERMISSION,
)

AEM_CUSTOMER_ADMIN_CLIENT_PERMISSIONS = (
    ADD_CLIENT_PERMISSION,
)

AEM_CUSTOMER_USER_CLIENT_PERMISSIONS = (
)

# CUSTOMER PERMISSIONS
AEM_ADMIN_CUSTOMER_PERMISSIONS = (
)

AEM_EMPLOYEE_CUSTOMER_PERMISSIONS = (
)

AEM_CUSTOMER_SUPER_USER_CUSTOMER_PERMISSIONS = (
    ADD_CUSTOMER_PERMISSION,
)

AEM_CUSTOMER_ADMIN_CUSTOMER_PERMISSIONS = (
    ADD_CUSTOMER_PERMISSION,
)

AEM_CUSTOMER_USER_CUSTOMER_PERMISSIONS = (
)

# COMPANY PERMISSIONS
AEM_ADMIN_COMPANY_PERMISSIONS = (
    ADD_COMPANY_PERMISSION,
)

AEM_EMPLOYEE_COMPANY_PERMISSIONS = (
    ADD_COMPANY_PERMISSION,
)

AEM_CUSTOMER_SUPER_USER_COMPANY_PERMISSIONS = (

)

AEM_CUSTOMER_ADMIN_COMPANY_PERMISSIONS = (
)

AEM_CUSTOMER_USER_COMPANY_PERMISSIONS = (
)
