# Generated by Django 2.1.3 on 2018-12-11 18:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.CharField(default=0, max_length=16)),
                ('mobile_number', models.CharField(blank=True, max_length=14, null=True)),
                ('landline_number', models.CharField(blank=True, max_length=14, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('system_details', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_deleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='clients.Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='company.Company')),
            ],
        ),
    ]
