# Generated by Django 2.1.3 on 2018-12-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='client',
            new_name='clients',
        ),
    ]
