# Generated by Django 2.1.3 on 2018-12-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20181211_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='clients',
            new_name='client',
        ),
    ]
