# Generated by Django 2.1.3 on 2018-12-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companymodule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymodule',
            name='description',
        ),
    ]
