# Generated by Django 2.1.3 on 2018-12-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_companymodule_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodule',
            name='modules',
            field=models.ManyToManyField(to='company.Company'),
        ),
    ]
