# Generated by Django 2.1.3 on 2018-12-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companymodule_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymodule',
            name='modules',
        ),
        migrations.AddField(
            model_name='company',
            name='modules',
            field=models.ManyToManyField(to='company.CompanyModule'),
        ),
    ]
