# Generated by Django 2.1.3 on 2018-12-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20181223_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='modules',
            field=models.ManyToManyField(blank=True, null=True, to='company.CompanyModule'),
        ),
    ]
