# Generated by Django 2.1.3 on 2018-12-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20181224_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodule',
            name='image_url',
            field=models.CharField(default=123, max_length=256),
            preserve_default=False,
        ),
    ]
