# Generated by Django 2.1.3 on 2018-11-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aemauthentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Super Admin'), (2, 'Company Super Admin'), (3, 'Full Office Staff'), (4, 'Partial Office Staff'), (5, 'Full Engineer'), (6, 'Partial Engineer')], default=0),
        ),
    ]
