# Generated by Django 2.1.3 on 2018-11-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aemauthentication', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'AEM Super Admin'), (2, 'Company Super Admin'), (3, 'Full Office Staff'), (4, 'Partial Office Staff'), (5, 'Full Engineer'), (6, 'Partial Engineer')], default=0),
        ),
    ]
