# Generated by Django 2.1.3 on 2018-11-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aemauthentication', '0004_auto_20181128_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
