# Generated by Django 2.1.3 on 2018-12-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20181204_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aemgroup',
            name='slug_field',
            field=models.SlugField(unique=True),
        ),
    ]
